import { AMCCompany } from "@/types";

export const STATES = [
"All States",
"AL",
"AK",
"AZ",
"AR",
"CA",
"CO",
"CT",
"DE",
"FL",
"GA",
"HI",
"ID",
"IL",
"IN",
"IA",
"KS",
"KY",
"LA",
"ME",
"MD",
"MA",
"MI",
"MN",
"MS",
"MO",
"MT",
"NE",
"NV",
"NH",
"NJ",
"NM",
"NY",
"NC",
"ND",
"OH",
"OK",
"OR",
"PA",
"RI",
"SC",
"SD",
"TN",
"TX",
"UT",
"VT",
"VA",
"WA",
"WV",
"WI",
"WY"] as
const;

export const COMPANIES: AMCCompany[] = [
{
  id: "amc-1",
  name: "Precision Valuation Services",
  phone: "(800) 555-0123",
  email: "info@precisionvaluations.com",
  state: "CA",
  website: "https://precisionvaluations.com",
  signupUrl: "https://precisionvaluations.com/signup"
},
{
  id: "amc-2",
  name: "BluePeak Appraisal Management",
  phone: "(877) 555-0147",
  email: "support@bluepeakamc.com",
  state: "TX",
  website: "https://bluepeakamc.com",
  signupUrl: "https://bluepeakamc.com/register"
},
{
  id: "amc-3",
  name: "UrbanEdge Valuation Group",
  phone: "(866) 555-0199",
  email: "team@urbanedgeval.com",
  state: "NY",
  website: "https://urbanedgeval.com",
  signupUrl: "https://urbanedgeval.com/vendors"
},
{
  id: "amc-4",
  name: "SunCoast AMC",
  phone: "(888) 555-0172",
  email: "hello@suncoastamc.com",
  state: "FL",
  website: "https://suncoastamc.com",
  signupUrl: "https://suncoastamc.com/sign-up"
},
{
  id: "amc-5",
  name: "Heartland Valuation Network",
  phone: "(855) 555-0114",
  email: "partners@heartlandvn.com",
  state: "IL",
  website: "https://heartlandvn.com",
  signupUrl: "https://heartlandvn.com/appraisers"
},
{
  id: "amc-6",
  name: "Atlantic Coast Valuations",
  phone: "(844) 555-0165",
  email: "vendors@atlanticcoastval.com",
  state: "NC",
  website: "https://atlanticcoastval.com",
  signupUrl: "https://atlanticcoastval.com/appraiser-signup"
},
{
  id: "amc-7",
  name: "Mountain View AMC",
  phone: "(866) 555-0198",
  email: "appraisers@mountainviewamc.com",
  state: "CO",
  website: "https://mountainviewamc.com",
  signupUrl: "https://mountainviewamc.com/register-appraiser"
},
{
  id: "amc-8",
  name: "Northwest Property Solutions",
  phone: "(877) 555-0134",
  email: "join@nwpropsolutions.com",
  state: "WA",
  website: "https://nwpropsolutions.com",
  signupUrl: "https://nwpropsolutions.com/vendor-portal"
}];