# This is a config for E2B sandbox template.
# You can use template ID (ob19xtpqde8bn1d6ws8x) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ob19xtpqde8bn1d6ws8x") # Sync sandbox
# sandbox = await AsyncSandbox.create("ob19xtpqde8bn1d6ws8x") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ob19xtpqde8bn1d6ws8x')

team_id = "b9e3fb7b-1546-4d96-85c8-05e5ed0c0eb5"
dockerfile = "e2b.Dockerfile"
template_id = "ob19xtpqde8bn1d6ws8x"
